jQuery(document).ready(function($){
	var form_action = $('.md_api').attr('action');
	//tabs
	$( "#tabs" ).tabs();
	$( "#tabs" ).on( "tabsactivate", function( event, ui ) {
		$('.current_tab').val(ui.newPanel.selector);
		var current_tab = $('.current_tab').val();
		$('.md_api').attr('action', form_action  + current_tab);
		window.location.hash = current_tab; 
	});
	
	var current_input_id = '';
	var list_background_color = 'mwp_list_main_background';
	var list_primary_color = 'mwp_list_font_color';
	var list_second_background_color = 'mwp_list_secondary_background';
	var list_second_color = 'mwp_list_hover_font_color';
	var mwp_list_main_content_font_color = 'mwp_list_main_content_font_color';
	var mwp_list_active_label = 'mwp_list_active_label';
	var mwp_list_main_content_second_font_color = 'mwp_list_main_content_second_font_color';
	var mwp_list_main_content_heading_color = 'mwp_list_main_content_heading_color';
	var mwp_list_border_color = 'mwp_list_border_color';
	var mwp_details_tab_active_background = 'mwp_details_tab_active_background';
	var mwp_details_tab_active_fontcolor = 'mwp_details_tab_active_fontcolor';
	var mwp_details_tab_inactive_background = 'mwp_details_tab_inactive_background';
	var mwp_details_tab_inactive_fontcolor = 'mwp_details_tab_inactive_fontcolor';
	var mwp_details_main_page_background = 'mwp_details_main_page_background';
	var mwp_details_main_background = 'mwp_details_main_background';
	var mwp_details_main_font_color = 'mwp_details_main_font_color';
	var mwp_details_secondary_background = 'mwp_details_secondary_background';
	var mwp_details_secondary_font_color = 'mwp_details_secondary_font_color';
	var mwp_details_content_main_fontcolor = 'mwp_details_content_main_fontcolor';
	var mwp_details_content_main_heading_fontcolor = 'mwp_details_content_main_heading_fontcolor';
	var mwp_details_content_secondary_fontcolor = 'mwp_details_content_secondary_fontcolor';
	var mwp_details_content_border_color = 'mwp_details_content_border_color';
	var mwp_button_main_background = 'mwp_button_main_background';
	var mwp_button_font_color = 'mwp_button_font_color';
	var mwp_button_secondary_background = 'mwp_button_secondary_background';
	var mwp_button_secondary_fontcolor = 'mwp_button_secondary_fontcolor';
	var mwp_button_border_color = 'mwp_button_border_color';
	var mwp_search_main_page_background = 'mwp_search_main_page_background';
	var mwp_header_main_background_color = 'mwp_header_main_background_color';
	var mwp_header_secondary_background_color = 'mwp_header_secondary_background_color';
	var mwp_header_primary_font_color = 'mwp_header_primary_font_color';
	var mwp_header_secondary_font_color = 'mwp_header_secondary_font_color';
	var mwp_header_heading_color = 'mwp_header_heading_color';
	var mwp_header_border_color = 'mwp_header_border_color';
	var mwp_details_tab_hover_background = 'mwp_details_tab_hover_background';
	var mwp_details_tab_hover_font_color = 'mwp_details_tab_hover_font_color';
	
	var color_input = '#'+list_background_color+ ','
	+'#'+list_primary_color+','
	+'#'+list_second_background_color+','
	+'#'+list_second_color+','
	+'#'+mwp_list_active_label+','
	+'#'+mwp_list_main_content_font_color+','
	+'#'+mwp_list_main_content_second_font_color+','
	+'#'+mwp_list_main_content_heading_color+','
	+'#'+mwp_list_border_color+','
	+'#'+mwp_details_tab_active_background+','
	+'#'+mwp_details_tab_active_fontcolor+','
	+'#'+mwp_details_tab_inactive_background+','
	+'#'+mwp_details_tab_inactive_fontcolor+','
	+'#'+mwp_details_main_page_background+','
	+'#'+mwp_details_main_background+','
	+'#'+mwp_details_main_font_color+','
	+'#'+mwp_details_secondary_background+','
	+'#'+mwp_details_secondary_font_color+','
	+'#'+mwp_details_content_main_fontcolor+','
	+'#'+mwp_details_content_main_heading_fontcolor+','
	+'#'+mwp_details_content_secondary_fontcolor+','
	+'#'+mwp_details_content_border_color+','
	+'#'+mwp_details_tab_hover_background+','
	+'#'+mwp_details_tab_hover_font_color+','
	+'#'+mwp_button_main_background+','
	+'#'+mwp_button_font_color+','
	+'#'+mwp_button_secondary_background+','
	+'#'+mwp_button_secondary_fontcolor+','
	+'#'+mwp_button_border_color+','
	+'#'+mwp_search_main_page_background+','
	+'#'+mwp_header_main_background_color+','
	+'#'+mwp_header_secondary_background_color+','
	+'#'+mwp_header_primary_font_color+','
	+'#'+mwp_header_secondary_font_color+','
	+'#'+mwp_header_heading_color+','
	+'#'+mwp_header_border_color
	;	
	
	$(color_input).ColorPicker({
		onShow: function (colpkr) {
			$(colpkr).fadeIn(500);
			return false;
		},
		onHide: function (colpkr) {
			$(colpkr).fadeOut(500);
			return false;
		},
		onChange: function (hsb, hex, rgb) {
			$('#' + current_input_id).val('#' + hex);
			$('.' + current_input_id + '-sample').css('backgroundColor', '#' + hex);
		},
		onSubmit: function(hsb, hex, rgb, el) {
			$(el).val(hex);
			$(el).ColorPickerHide();
		},
		onBeforeShow: function () {
			current_input_id = $(this).attr('id');
			$(this).ColorPickerSetColor(this.value);
		}
	})
	.bind('keyup', function(){
		$(this).ColorPickerSetColor(this.value);
	});
	$('.berkshire-hathaway').click(function(e){
		e.preventDefault();
		$('#'+list_background_color).val('#ffffff');
		$('.'+list_background_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_list_active_label).val('#060');
		$('.'+mwp_list_active_label+'-sample').css('backgroundColor', '#060');
		$('#'+list_primary_color).val('#542549');
		$('.'+list_primary_color+'-sample').css('backgroundColor', '#542549');
		$('#'+list_second_background_color).val('#542549');
		$('.'+list_second_background_color+'-sample').css('backgroundColor', '#542549');
		$('#'+list_second_color).val('#843b73');
		$('.'+list_second_color+'-sample').css('backgroundColor', '#843b73');
		$('#'+mwp_list_main_content_font_color).val('#542549');
		$('.'+mwp_list_main_content_font_color+'-sample').css('backgroundColor', '#542549');
		$('#'+mwp_list_main_content_second_font_color).val('#ffffff');
		$('.'+mwp_list_main_content_second_font_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_list_main_content_heading_color).val('#ffffff');
		$('.'+mwp_list_main_content_heading_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_list_border_color).val('#dddddd');
		$('.'+mwp_list_border_color+'-sample').css('backgroundColor', '#dddddd');
		$('#'+mwp_details_tab_active_background).val('#542549');
		$('.'+mwp_details_tab_active_background+'-sample').css('backgroundColor', '#542549');
		$('#'+mwp_details_tab_active_fontcolor).val('#ffffff');
		$('.'+mwp_details_tab_active_fontcolor+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_details_tab_inactive_background).val('#ac719e');
		$('.'+mwp_details_tab_inactive_background+'-sample').css('backgroundColor', '#ac719e');
		$('#'+mwp_details_tab_inactive_fontcolor).val('#ffffff');
		$('.'+mwp_details_tab_inactive_fontcolor+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_details_main_page_background).val('#ffffff');
		$('.'+mwp_details_main_page_background+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_details_main_background).val('#ac719e');
		$('.'+mwp_details_main_background+'-sample').css('backgroundColor', '#ac719e');
		$('#'+mwp_details_main_font_color).val('#222222');
		$('.'+mwp_details_main_font_color+'-sample').css('backgroundColor', '#222222');
		$('#'+mwp_details_secondary_background).val('#f0f0f0');
		$('.'+mwp_details_secondary_background+'-sample').css('backgroundColor', '#f0f0f0');
		$('#'+mwp_details_secondary_font_color).val('#ac719e');
		$('.'+mwp_details_secondary_font_color+'-sample').css('backgroundColor', '#ac719e');
		$('#'+mwp_details_content_main_fontcolor).val('#542549');
		$('.'+mwp_details_content_main_fontcolor+'-sample').css('backgroundColor', '#542549');
		$('#'+mwp_details_content_main_heading_fontcolor).val('#542549');
		$('.'+mwp_details_content_main_heading_fontcolor+'-sample').css('backgroundColor', '#542549');
		$('#'+mwp_details_content_secondary_fontcolor).val('#000000');
		$('.'+mwp_details_content_secondary_fontcolor+'-sample').css('backgroundColor', '#000000');
		$('.'+mwp_details_content_border_color+'-sample').css('backgroundColor', '#d8d6d7');
		$('#'+mwp_details_content_border_color).val('#d8d6d7');
		$('.'+mwp_details_tab_hover_background+'-sample').css('backgroundColor', '#542549');
		$('#'+mwp_details_tab_hover_background).val('#542549');
		$('.'+mwp_details_tab_hover_font_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_details_tab_hover_font_color).val('#ffffff');
		$('#'+mwp_button_main_background).val('#e8e8e8');
		$('.'+mwp_button_main_background+'-sample').css('backgroundColor', '#e8e8e8');
		$('#'+mwp_button_font_color).val('#542549');
		$('.'+mwp_button_font_color+'-sample').css('backgroundColor', '#542549');
		$('#'+mwp_button_secondary_background).val('#e8e8e8');
		$('.'+mwp_button_secondary_background+'-sample').css('backgroundColor', '#e8e8e8');
		$('#'+mwp_button_secondary_fontcolor).val('#542549');
		$('.'+mwp_button_secondary_fontcolor+'-sample').css('backgroundColor', '#542549');
		$('#'+mwp_button_border_color).val('#e8e8e8');
		$('.'+mwp_button_border_color+'-sample').css('backgroundColor', '#e8e8e8');
		$('#'+mwp_search_main_page_background).val('#ffffff');
		$('.'+mwp_search_main_page_background+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_header_main_background_color).val('#542549');
		$('.'+mwp_header_main_background_color+'-sample').css('backgroundColor', '#542549');
		$('#'+mwp_header_secondary_background_color).val('#662b58');
		$('.'+mwp_header_secondary_background_color+'-sample').css('backgroundColor', '#662b58');
		$('#'+mwp_header_primary_font_color).val('#ffffff');
		$('.'+mwp_header_primary_font_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_header_secondary_font_color).val('#ffffff');
		$('.'+mwp_header_secondary_font_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_header_heading_color).val('#ffffff');
		$('.'+mwp_header_heading_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_header_border_color).val('#542549');
		$('.'+mwp_header_border_color+'-sample').css('backgroundColor', '#542549');
	});
	$('.century-twenty-one').click(function(e){
		e.preventDefault();
		$('#'+list_background_color).val('#ffffff');
		$('.'+list_background_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_list_active_label).val('#060');
		$('.'+mwp_list_active_label+'-sample').css('backgroundColor', '#060');
		$('#'+list_second_background_color).val('#000000');
		$('.'+list_second_background_color+'-sample').css('backgroundColor', '#000000');
		$('#'+list_primary_color).val('#000000');
		$('.'+list_primary_color+'-sample').css('backgroundColor', '#000000');
		$('#'+list_second_color).val('#ecb429');
		$('.'+list_second_color+'-sample').css('backgroundColor', '#ecb429');
		$('#'+mwp_list_main_content_font_color).val('#000000');
		$('.'+mwp_list_main_content_font_color+'-sample').css('backgroundColor', '#000000');
		$('#'+mwp_list_main_content_second_font_color).val('#ecb429');
		$('.'+mwp_list_main_content_second_font_color+'-sample').css('backgroundColor', '#ecb429');
		$('#'+mwp_list_main_content_heading_color).val('#ecb429');
		$('.'+mwp_list_main_content_heading_color+'-sample').css('backgroundColor', '#ecb429');
		$('#'+mwp_list_border_color).val('#dddddd');
		$('.'+mwp_list_border_color+'-sample').css('backgroundColor', '#dddddd');
		$('#'+mwp_details_tab_active_background).val('#ecb429');
		$('.'+mwp_details_tab_active_background+'-sample').css('backgroundColor', '#ecb429');
		$('#'+mwp_details_tab_inactive_background).val('#262626');
		$('.'+mwp_details_tab_inactive_background+'-sample').css('backgroundColor', '#262626');
		$('#'+mwp_details_main_page_background).val('#000000');
		$('.'+mwp_details_main_page_background+'-sample').css('backgroundColor', '#000000');
		$('#'+mwp_details_main_background).val('#ecb429');
		$('.'+mwp_details_main_background+'-sample').css('backgroundColor', '#ecb429');
		$('#'+mwp_details_tab_active_fontcolor).val('#000000');
		$('.'+mwp_details_tab_active_fontcolor+'-sample').css('backgroundColor', '#000000');
		$('#'+mwp_details_tab_inactive_fontcolor).val('#ecb429');
		$('.'+mwp_details_tab_inactive_fontcolor+'-sample').css('backgroundColor', '#ecb429');
		$('#'+mwp_details_main_font_color).val('#ffffff');
		$('.'+mwp_details_main_font_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_details_secondary_background).val('#262626');
		$('.'+mwp_details_secondary_background+'-sample').css('backgroundColor', '#262626');
		$('#'+mwp_details_secondary_font_color).val('#ecb429');
		$('.'+mwp_details_secondary_font_color+'-sample').css('backgroundColor', '#ecb429');
		$('#'+mwp_details_content_main_fontcolor).val('#000000');
		$('.'+mwp_details_content_main_fontcolor+'-sample').css('backgroundColor', '#000000');
		$('#'+mwp_details_content_main_heading_fontcolor).val('#ecb429');
		$('.'+mwp_details_content_main_heading_fontcolor+'-sample').css('backgroundColor', '#ecb429');
		$('#'+mwp_details_content_secondary_fontcolor).val('#000000');
		$('.'+mwp_details_content_secondary_fontcolor+'-sample').css('backgroundColor', '#000000');
		$('.'+mwp_details_content_border_color+'-sample').css('backgroundColor', '#262626');
		$('#'+mwp_details_content_border_color).val('#262626');
		$('.'+mwp_details_tab_hover_background+'-sample').css('backgroundColor', '#ecb429');
		$('#'+mwp_details_tab_hover_background).val('#ecb429');
		$('.'+mwp_details_tab_hover_font_color+'-sample').css('backgroundColor', '#ecb429');
		$('#'+mwp_details_tab_hover_font_color).val('#ecb429');
		$('#'+mwp_button_main_background).val('#000000');
		$('.'+mwp_button_main_background+'-sample').css('backgroundColor', '#000000');
		$('#'+mwp_button_font_color).val('#ecb429');
		$('.'+mwp_button_font_color+'-sample').css('backgroundColor', '#ecb429');
		$('#'+mwp_button_secondary_background).val('#000000');
		$('.'+mwp_button_secondary_background+'-sample').css('backgroundColor', '#000000');
		$('#'+mwp_button_secondary_fontcolor).val('#ecb429');
		$('.'+mwp_button_secondary_fontcolor+'-sample').css('backgroundColor', '#ecb429');
		$('#'+mwp_button_border_color).val('#ecb429');
		$('.'+mwp_button_border_color+'-sample').css('backgroundColor', '#ecb429');
		$('#'+mwp_search_main_page_background).val('#ffffff');
		$('.'+mwp_search_main_page_background+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_header_main_background_color).val('#ecb429');
		$('.'+mwp_header_main_background_color+'-sample').css('backgroundColor', '#ecb429');
		$('#'+mwp_header_secondary_background_color).val('#a17100');
		$('.'+mwp_header_secondary_background_color+'-sample').css('backgroundColor', '#a17100');
		$('#'+mwp_header_primary_font_color).val('#ffffff');
		$('.'+mwp_header_primary_font_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_header_secondary_font_color).val('#ffffff');
		$('.'+mwp_header_secondary_font_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_header_heading_color).val('#ffffff');
		$('.'+mwp_header_heading_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_header_border_color).val('#ecb429');
		$('.'+mwp_header_border_color+'-sample').css('backgroundColor', '#ecb429');
	});
	$('.coldwell-banker').click(function(e){
		e.preventDefault();
		$('#'+list_background_color).val('#ffffff');
		$('.'+list_background_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_list_active_label).val('#060');
		$('.'+mwp_list_active_label+'-sample').css('backgroundColor', '#060');
		$('#'+list_second_background_color).val('#00275e');
		$('.'+list_second_background_color+'-sample').css('backgroundColor', '#00275e');
		$('#'+list_primary_color).val('#00275e');
		$('.'+list_primary_color+'-sample').css('backgroundColor', '#00275e');
		$('#'+list_second_color).val('#ffffff');
		$('.'+list_second_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_list_main_content_font_color).val('#333333');
		$('.'+mwp_list_main_content_font_color+'-sample').css('backgroundColor', '#333333');
		$('#'+mwp_list_main_content_second_font_color).val('#ffffff');
		$('.'+mwp_list_main_content_second_font_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_list_main_content_heading_color).val('#ffffff');
		$('.'+mwp_list_main_content_heading_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_list_border_color).val('#dddddd');
		$('.'+mwp_list_border_color+'-sample').css('backgroundColor', '#dddddd');
		$('#'+mwp_details_tab_active_background).val('#00275e');
		$('.'+mwp_details_tab_active_background+'-sample').css('backgroundColor', '#00275e');
		$('#'+mwp_details_tab_active_fontcolor).val('#ffffff');
		$('.'+mwp_details_tab_active_fontcolor+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_details_tab_inactive_background).val('#003e95');
		$('.'+mwp_details_tab_inactive_background+'-sample').css('backgroundColor', '#003e95');
		$('#'+mwp_details_tab_inactive_fontcolor).val('#ffffff');
		$('.'+mwp_details_tab_inactive_fontcolor+'-sample').css('backgroundColor', '#ffffff');
		$('.'+mwp_details_tab_hover_background+'-sample').css('backgroundColor', '#00275e');
		$('#'+mwp_details_tab_hover_background).val('#00275e');
		$('.'+mwp_details_tab_hover_font_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_details_tab_hover_font_color).val('#ffffff');
		$('#'+mwp_details_main_page_background).val('#ffffff');
		$('.'+mwp_details_main_page_background+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_details_main_background).val('#003e95');
		$('.'+mwp_details_main_background+'-sample').css('backgroundColor', '#003e95');
		$('#'+mwp_details_main_font_color).val('#222222');
		$('.'+mwp_details_main_font_color+'-sample').css('backgroundColor', '#222222');
		$('#'+mwp_details_content_main_fontcolor).val('#222222');
		$('.'+mwp_details_content_main_fontcolor+'-sample').css('backgroundColor', '#222222');
		$('#'+mwp_details_content_main_heading_fontcolor).val('#00275e');
		$('.'+mwp_details_content_main_heading_fontcolor+'-sample').css('backgroundColor', '#00275e');
		$('#'+mwp_details_secondary_background).val('#d9d9d9');
		$('.'+mwp_details_secondary_background+'-sample').css('backgroundColor', '#d9d9d9');
		$('#'+mwp_details_secondary_font_color).val('#003e95');
		$('.'+mwp_details_secondary_font_color+'-sample').css('backgroundColor', '#003e95');
		$('#'+mwp_details_content_secondary_fontcolor).val('#222222');
		$('.'+mwp_details_content_secondary_fontcolor+'-sample').css('backgroundColor', '#222222');
		$('.'+mwp_details_content_border_color+'-sample').css('backgroundColor', '#c7c7c7');
		$('#'+mwp_details_content_border_color).val('#c7c7c7');
		$('#'+mwp_search_main_page_background).val('#ffffff');
		$('.'+mwp_search_main_page_background+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_button_main_background).val('#ffffff');
		$('.'+mwp_button_main_background+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_button_font_color).val('#00275e');
		$('.'+mwp_button_font_color+'-sample').css('backgroundColor', '#00275e');
		$('#'+mwp_button_secondary_background).val('#ffffff');
		$('.'+mwp_button_secondary_background+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_button_secondary_fontcolor).val('#00275e');
		$('.'+mwp_button_secondary_fontcolor+'-sample').css('backgroundColor', '#00275e');
		$('#'+mwp_button_border_color).val('#ffffff');
		$('.'+mwp_button_border_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_header_main_background_color).val('#00275e');
		$('.'+mwp_header_main_background_color+'-sample').css('backgroundColor', '#00275e');
		$('#'+mwp_header_secondary_background_color).val('#00122b');
		$('.'+mwp_header_secondary_background_color+'-sample').css('backgroundColor', '#00122b');
		$('#'+mwp_header_primary_font_color).val('#ffffff');
		$('.'+mwp_header_primary_font_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_header_secondary_font_color).val('#ffffff');
		$('.'+mwp_header_secondary_font_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_header_heading_color).val('#ffffff');
		$('.'+mwp_header_heading_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_header_border_color).val('#00275e');
		$('.'+mwp_header_border_color+'-sample').css('backgroundColor', '#00275e');
	});
	$('.digmrealty').click(function(e){
		e.preventDefault();
		$('#'+list_background_color).val('#ffffff');
		$('.'+list_background_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_list_active_label).val('#060');
		$('.'+mwp_list_active_label+'-sample').css('backgroundColor', '#060');
		$('#'+list_second_background_color).val('#00275e');
		$('.'+list_second_background_color+'-sample').css('backgroundColor', '#00275e');
		$('#'+list_primary_color).val('#00275e');
		$('.'+list_primary_color+'-sample').css('backgroundColor', '#00275e');
		$('#'+list_second_color).val('#ffffff');
		$('.'+list_second_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_list_main_content_font_color).val('#333333');
		$('.'+mwp_list_main_content_font_color+'-sample').css('backgroundColor', '#333333');
		$('#'+mwp_list_main_content_second_font_color).val('#ffffff');
		$('.'+mwp_list_main_content_second_font_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_list_main_content_heading_color).val('#ffffff');
		$('.'+mwp_list_main_content_heading_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_list_border_color).val('#dddddd');
		$('.'+mwp_list_border_color+'-sample').css('backgroundColor', '#dddddd');
		$('#'+mwp_details_tab_active_background).val('#000f24');
		$('.'+mwp_details_tab_active_background+'-sample').css('backgroundColor', '#000f24');
		$('#'+mwp_details_tab_active_fontcolor).val('#ffffff');
		$('.'+mwp_details_tab_active_fontcolor+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_details_tab_inactive_background).val('#001738');
		$('.'+mwp_details_tab_inactive_background+'-sample').css('backgroundColor', '#001738');
		$('#'+mwp_details_tab_inactive_fontcolor).val('#ffffff');
		$('.'+mwp_details_tab_inactive_fontcolor+'-sample').css('backgroundColor', '#ffffff');
		$('.'+mwp_details_tab_hover_background+'-sample').css('backgroundColor', '#000f24');
		$('#'+mwp_details_tab_hover_background).val('#000f24');
		$('.'+mwp_details_tab_hover_font_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_details_tab_hover_font_color).val('#ffffff');
		$('#'+mwp_details_main_page_background).val('#ffffff');
		$('.'+mwp_details_main_page_background+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_details_main_background).val('#001738');
		$('.'+mwp_details_main_background+'-sample').css('backgroundColor', '#001738');
		$('#'+mwp_details_main_font_color).val('#222222');
		$('.'+mwp_details_main_font_color+'-sample').css('backgroundColor', '#222222');
		$('#'+mwp_details_content_main_fontcolor).val('#222222');
		$('.'+mwp_details_content_main_fontcolor+'-sample').css('backgroundColor', '#222222');
		$('#'+mwp_details_content_main_heading_fontcolor).val('#222222');
		$('.'+mwp_details_content_main_heading_fontcolor+'-sample').css('backgroundColor', '#222222');
		$('#'+mwp_details_secondary_background).val('#e8e8e8');
		$('.'+mwp_details_secondary_background+'-sample').css('backgroundColor', '#e8e8e8');
		$('#'+mwp_details_secondary_font_color).val('#003e95');
		$('.'+mwp_details_secondary_font_color+'-sample').css('backgroundColor', '#003e95');
		$('#'+mwp_details_content_secondary_fontcolor).val('#333333');
		$('.'+mwp_details_content_secondary_fontcolor+'-sample').css('backgroundColor', '#333333');
		$('.'+mwp_details_content_border_color+'-sample').css('backgroundColor', '#001738');
		$('#'+mwp_details_content_border_color).val('#001738');
		$('#'+mwp_search_main_page_background).val('#ffffff');
		$('.'+mwp_search_main_page_background+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_button_main_background).val('#003e95');
		$('.'+mwp_button_main_background+'-sample').css('backgroundColor', '#003e95');
		$('#'+mwp_button_font_color).val('#ffffff');
		$('.'+mwp_button_font_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_button_secondary_background).val('#00275e');
		$('.'+mwp_button_secondary_background+'-sample').css('backgroundColor', '#00275e');
		$('#'+mwp_button_secondary_fontcolor).val('#ffffff');
		$('.'+mwp_button_secondary_fontcolor+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_button_border_color).val('#003e95');
		$('.'+mwp_button_border_color+'-sample').css('backgroundColor', '#003e95');
		$('#'+mwp_header_main_background_color).val('#001738');
		$('.'+mwp_header_main_background_color+'-sample').css('backgroundColor', '#001738');
		$('#'+mwp_header_secondary_background_color).val('#000f24');
		$('.'+mwp_header_secondary_background_color+'-sample').css('backgroundColor', '#000f24');
		$('#'+mwp_header_primary_font_color).val('#ffffff');
		$('.'+mwp_header_primary_font_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_header_secondary_font_color).val('#ffffff');
		$('.'+mwp_header_secondary_font_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_header_heading_color).val('#ffffff');
		$('.'+mwp_header_heading_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_header_border_color).val('#001738');
		$('.'+mwp_header_border_color+'-sample').css('backgroundColor', '#001738');
	});
	$('.dreamhomesofcabo').click(function(e){
		e.preventDefault();
		$('#'+list_background_color).val('#ffffff');
		$('.'+list_background_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_list_active_label).val('#060');
		$('.'+mwp_list_active_label+'-sample').css('backgroundColor', '#060');
		$('#'+list_second_background_color).val('#00275e');
		$('.'+list_second_background_color+'-sample').css('backgroundColor', '#00275e');
		$('#'+list_primary_color).val('#00275e');
		$('.'+list_primary_color+'-sample').css('backgroundColor', '#00275e');
		$('#'+list_second_color).val('#ffffff');
		$('.'+list_second_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_list_main_content_font_color).val('#333333');
		$('.'+mwp_list_main_content_font_color+'-sample').css('backgroundColor', '#333333');
		$('#'+mwp_list_main_content_second_font_color).val('#ffffff');
		$('.'+mwp_list_main_content_second_font_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_list_main_content_heading_color).val('#ffffff');
		$('.'+mwp_list_main_content_heading_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_list_border_color).val('#dddddd');
		$('.'+mwp_list_border_color+'-sample').css('backgroundColor', '#dddddd');
		$('#'+mwp_details_tab_active_background).val('#6e1614');
		$('.'+mwp_details_tab_active_background+'-sample').css('backgroundColor', '#6e1614');
		$('#'+mwp_details_tab_active_fontcolor).val('#d9cfac');
		$('.'+mwp_details_tab_active_fontcolor+'-sample').css('backgroundColor', '#d9cfac');
		$('#'+mwp_details_tab_inactive_background).val('#bcaa7a');
		$('.'+mwp_details_tab_inactive_background+'-sample').css('backgroundColor', '#bcaa7a');
		$('#'+mwp_details_tab_inactive_fontcolor).val('#6e1614');
		$('.'+mwp_details_tab_inactive_fontcolor+'-sample').css('backgroundColor', '#6e1614');
		$('.'+mwp_details_tab_hover_background+'-sample').css('backgroundColor', '#6e1614');
		$('#'+mwp_details_tab_hover_background).val('#6e1614');
		$('.'+mwp_details_tab_hover_font_color+'-sample').css('backgroundColor', '#d9cfac');
		$('#'+mwp_details_tab_hover_font_color).val('#d9cfac');
		$('#'+mwp_details_main_page_background).val('#d9cfac');
		$('.'+mwp_details_main_page_background+'-sample').css('backgroundColor', '#d9cfac');
		$('#'+mwp_details_main_background).val('#6e1614');
		$('.'+mwp_details_main_background+'-sample').css('backgroundColor', '#6e1614');
		$('#'+mwp_details_main_font_color).val('#54492e');
		$('.'+mwp_details_main_font_color+'-sample').css('backgroundColor', '#54492e');
		$('#'+mwp_details_content_main_fontcolor).val('#6e1614');
		$('.'+mwp_details_content_main_fontcolor+'-sample').css('backgroundColor', '#6e1614');
		$('#'+mwp_details_content_main_heading_fontcolor).val('#6e1614');
		$('.'+mwp_details_content_main_heading_fontcolor+'-sample').css('backgroundColor', '#6e1614');
		$('#'+mwp_details_secondary_background).val('#c4b993');
		$('.'+mwp_details_secondary_background+'-sample').css('backgroundColor', '#c4b993');
		$('#'+mwp_details_secondary_font_color).val('#6e1614');
		$('.'+mwp_details_secondary_font_color+'-sample').css('backgroundColor', '#6e1614');
		$('#'+mwp_details_content_secondary_fontcolor).val('#54492e');
		$('.'+mwp_details_content_secondary_fontcolor+'-sample').css('backgroundColor', '#54492e');
		$('.'+mwp_details_content_border_color+'-sample').css('backgroundColor', '#bcaa7a');
		$('#'+mwp_details_content_border_color).val('#bcaa7a');
		$('#'+mwp_search_main_page_background).val('#d9cfac');
		$('.'+mwp_search_main_page_background+'-sample').css('backgroundColor', '#d9cfac');
		$('#'+mwp_button_main_background).val('#bcaa7a');
		$('.'+mwp_button_main_background+'-sample').css('backgroundColor', '#bcaa7a');
		$('#'+mwp_button_font_color).val('#6e1614');
		$('.'+mwp_button_font_color+'-sample').css('backgroundColor', '#6e1614');
		$('#'+mwp_button_secondary_background).val('#bcaa7a');
		$('.'+mwp_button_secondary_background+'-sample').css('backgroundColor', '#bcaa7a');
		$('#'+mwp_button_secondary_fontcolor).val('#6e1614');
		$('.'+mwp_button_secondary_fontcolor+'-sample').css('backgroundColor', '#6e1614');
		$('#'+mwp_button_border_color).val('#bcaa7a');
		$('.'+mwp_button_border_color+'-sample').css('backgroundColor', '#bcaa7a');
		$('#'+mwp_header_main_background_color).val('#6e1614');
		$('.'+mwp_header_main_background_color+'-sample').css('backgroundColor', '#6e1614');
		$('#'+mwp_header_secondary_background_color).val('#ab8f46');
		$('.'+mwp_header_secondary_background_color+'-sample').css('backgroundColor', '#ab8f46');
		$('#'+mwp_header_primary_font_color).val('#ffffff');
		$('.'+mwp_header_primary_font_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_header_secondary_font_color).val('#ffffff');
		$('.'+mwp_header_secondary_font_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_header_heading_color).val('#ffffff');
		$('.'+mwp_header_heading_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_header_border_color).val('#6e1614');
		$('.'+mwp_header_border_color+'-sample').css('backgroundColor', '#6e1614');
	});
	$('.era').click(function(e){
		e.preventDefault();
		$('#'+list_background_color).val('#ffffff');
		$('.'+list_background_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_list_active_label).val('#060');
		$('.'+mwp_list_active_label+'-sample').css('backgroundColor', '#060');
		$('#'+list_second_background_color).val('#00275e');
		$('.'+list_second_background_color+'-sample').css('backgroundColor', '#00275e');
		$('#'+list_primary_color).val('#00275e');
		$('.'+list_primary_color+'-sample').css('backgroundColor', '#00275e');
		$('#'+list_second_color).val('#ffffff');
		$('.'+list_second_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_list_main_content_font_color).val('#333333');
		$('.'+mwp_list_main_content_font_color+'-sample').css('backgroundColor', '#333333');
		$('#'+mwp_list_main_content_second_font_color).val('#ffffff');
		$('.'+mwp_list_main_content_second_font_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_list_main_content_heading_color).val('#ffffff');
		$('.'+mwp_list_main_content_heading_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_list_border_color).val('#dddddd');
		$('.'+mwp_list_border_color+'-sample').css('backgroundColor', '#dddddd');
		$('#'+mwp_details_tab_active_background).val('#c9042f');
		$('.'+mwp_details_tab_active_background+'-sample').css('backgroundColor', '#c9042f');
		$('#'+mwp_details_tab_active_fontcolor).val('#ffffff');
		$('.'+mwp_details_tab_active_fontcolor+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_details_tab_inactive_background).val('#e43b60');
		$('.'+mwp_details_tab_inactive_background+'-sample').css('backgroundColor', '#e43b60');
		$('#'+mwp_details_tab_inactive_fontcolor).val('#ffffff');
		$('.'+mwp_details_tab_inactive_fontcolor+'-sample').css('backgroundColor', '#ffffff');
		$('.'+mwp_details_tab_hover_background+'-sample').css('backgroundColor', '#c9042f');
		$('#'+mwp_details_tab_hover_background).val('#c9042f');
		$('.'+mwp_details_tab_hover_font_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_details_tab_hover_font_color).val('#ffffff');
		$('#'+mwp_details_main_page_background).val('#ffffff');
		$('.'+mwp_details_main_page_background+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_details_main_background).val('#c9042f');
		$('.'+mwp_details_main_background+'-sample').css('backgroundColor', '#c9042f');
		$('#'+mwp_details_main_font_color).val('#222222');
		$('.'+mwp_details_main_font_color+'-sample').css('backgroundColor', '#222222');
		$('#'+mwp_details_content_main_fontcolor).val('#c9042f');
		$('.'+mwp_details_content_main_fontcolor+'-sample').css('backgroundColor', '#c9042f');
		$('#'+mwp_details_content_main_heading_fontcolor).val('#222222');
		$('.'+mwp_details_content_main_heading_fontcolor+'-sample').css('backgroundColor', '#222222');
		$('#'+mwp_details_secondary_background).val('#f0f0f0');
		$('.'+mwp_details_secondary_background+'-sample').css('backgroundColor', '#f0f0f0');
		$('#'+mwp_details_secondary_font_color).val('#e43b60');
		$('.'+mwp_details_secondary_font_color+'-sample').css('backgroundColor', '#e43b60');
		$('#'+mwp_details_content_secondary_fontcolor).val('#000000');
		$('.'+mwp_details_content_secondary_fontcolor+'-sample').css('backgroundColor', '#000000');
		$('.'+mwp_details_content_border_color+'-sample').css('backgroundColor', '#c9042f');
		$('#'+mwp_details_content_border_color).val('#c9042f');
		$('#'+mwp_search_main_page_background).val('#ffffff');
		$('.'+mwp_search_main_page_background+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_button_main_background).val('#c9042f');
		$('.'+mwp_button_main_background+'-sample').css('backgroundColor', '#c9042f');
		$('#'+mwp_button_font_color).val('#ffffff');
		$('.'+mwp_button_font_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_button_secondary_background).val('#c9042f');
		$('.'+mwp_button_secondary_background+'-sample').css('backgroundColor', '#c9042f');
		$('#'+mwp_button_secondary_fontcolor).val('#ffffff');
		$('.'+mwp_button_secondary_fontcolor+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_button_border_color).val('#ffffff');
		$('.'+mwp_button_border_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_header_main_background_color).val('#ffffff');
		$('.'+mwp_header_main_background_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_header_secondary_background_color).val('#c9042f');
		$('.'+mwp_header_secondary_background_color+'-sample').css('backgroundColor', '#c9042f');
		$('#'+mwp_header_primary_font_color).val('#000000');
		$('.'+mwp_header_primary_font_color+'-sample').css('backgroundColor', '#000000');
		$('#'+mwp_header_secondary_font_color).val('#000000');
		$('.'+mwp_header_secondary_font_color+'-sample').css('backgroundColor', '#000000');
		$('#'+mwp_header_heading_color).val('#000000');
		$('.'+mwp_header_heading_color+'-sample').css('backgroundColor', '#000000');
		$('#'+mwp_header_border_color).val('#c9042f');
		$('.'+mwp_header_border_color+'-sample').css('backgroundColor', '#c9042f');
	});
	$('.exit-realty').click(function(e){
		e.preventDefault();
		$('#'+list_background_color).val('#ffffff');
		$('.'+list_background_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_list_active_label).val('#060');
		$('.'+mwp_list_active_label+'-sample').css('backgroundColor', '#060');
		$('#'+list_second_background_color).val('#00275e');
		$('.'+list_second_background_color+'-sample').css('backgroundColor', '#00275e');
		$('#'+list_primary_color).val('#00275e');
		$('.'+list_primary_color+'-sample').css('backgroundColor', '#00275e');
		$('#'+list_second_color).val('#ffffff');
		$('.'+list_second_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_list_main_content_font_color).val('#333333');
		$('.'+mwp_list_main_content_font_color+'-sample').css('backgroundColor', '#333333');
		$('#'+mwp_list_main_content_second_font_color).val('#ffffff');
		$('.'+mwp_list_main_content_second_font_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_list_main_content_heading_color).val('#ffffff');
		$('.'+mwp_list_main_content_heading_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_list_border_color).val('#dddddd');
		$('.'+mwp_list_border_color+'-sample').css('backgroundColor', '#dddddd');
		$('#'+mwp_details_tab_active_background).val('#007788');
		$('.'+mwp_details_tab_active_background+'-sample').css('backgroundColor', '#007788');
		$('#'+mwp_details_tab_active_fontcolor).val('#ffffff');
		$('.'+mwp_details_tab_active_fontcolor+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_details_tab_inactive_background).val('#d8d6d7');
		$('.'+mwp_details_tab_inactive_background+'-sample').css('backgroundColor', '#d8d6d7');
		$('#'+mwp_details_tab_inactive_fontcolor).val('#007788');
		$('.'+mwp_details_tab_inactive_fontcolor+'-sample').css('backgroundColor', '#007788');
		$('.'+mwp_details_tab_hover_background+'-sample').css('backgroundColor', '#007788');
		$('#'+mwp_details_tab_hover_background).val('#007788');
		$('.'+mwp_details_tab_hover_font_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_details_tab_hover_font_color).val('#ffffff');
		$('#'+mwp_details_main_page_background).val('#ffffff');
		$('.'+mwp_details_main_page_background+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_details_main_background).val('#007788');
		$('.'+mwp_details_main_background+'-sample').css('backgroundColor', '#007788');
		$('#'+mwp_details_main_font_color).val('#222222');
		$('.'+mwp_details_main_font_color+'-sample').css('backgroundColor', '#222222');
		$('#'+mwp_details_content_main_fontcolor).val('#000000');
		$('.'+mwp_details_content_main_fontcolor+'-sample').css('backgroundColor', '#000000');
		$('#'+mwp_details_content_main_heading_fontcolor).val('#222222');
		$('.'+mwp_details_content_main_heading_fontcolor+'-sample').css('backgroundColor', '#222222');
		$('#'+mwp_details_secondary_background).val('#f0f0f0');
		$('.'+mwp_details_secondary_background+'-sample').css('backgroundColor', '#f0f0f0');
		$('#'+mwp_details_secondary_font_color).val('#19b4ca');
		$('.'+mwp_details_secondary_font_color+'-sample').css('backgroundColor', '#19b4ca');
		$('#'+mwp_details_content_secondary_fontcolor).val('#000000');
		$('.'+mwp_details_content_secondary_fontcolor+'-sample').css('backgroundColor', '#000000');
		$('.'+mwp_details_content_border_color+'-sample').css('backgroundColor', '#b5b5b5');
		$('#'+mwp_details_content_border_color).val('#b5b5b5');
		$('#'+mwp_search_main_page_background).val('#ffffff');
		$('.'+mwp_search_main_page_background+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_button_main_background).val('#007788');
		$('.'+mwp_button_main_background+'-sample').css('backgroundColor', '#007788');
		$('#'+mwp_button_font_color).val('#ffffff');
		$('.'+mwp_button_font_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_button_secondary_background).val('#007788');
		$('.'+mwp_button_secondary_background+'-sample').css('backgroundColor', '#007788');
		$('#'+mwp_button_secondary_fontcolor).val('#ffffff');
		$('.'+mwp_button_secondary_fontcolor+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_button_border_color).val('#ffffff');
		$('.'+mwp_button_border_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_header_main_background_color).val('#ededed');
		$('.'+mwp_header_main_background_color+'-sample').css('backgroundColor', '#ededed');
		$('#'+mwp_header_secondary_background_color).val('#007788');
		$('.'+mwp_header_secondary_background_color+'-sample').css('backgroundColor', '#007788');
		$('#'+mwp_header_primary_font_color).val('#000000');
		$('.'+mwp_header_primary_font_color+'-sample').css('backgroundColor', '#000000');
		$('#'+mwp_header_secondary_font_color).val('#000000');
		$('.'+mwp_header_secondary_font_color+'-sample').css('backgroundColor', '#000000');
		$('#'+mwp_header_heading_color).val('#000000');
		$('.'+mwp_header_heading_color+'-sample').css('backgroundColor', '#000000');
		$('#'+mwp_header_border_color).val('#d1d1d1');
		$('.'+mwp_header_border_color+'-sample').css('backgroundColor', '#d1d1d1');
	});
	$('.keller-williams').click(function(e){
		e.preventDefault();
		$('#'+list_background_color).val('#ffffff');
		$('.'+list_background_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_list_active_label).val('#060');
		$('.'+mwp_list_active_label+'-sample').css('backgroundColor', '#060');
		$('#'+list_second_background_color).val('#00275e');
		$('.'+list_second_background_color+'-sample').css('backgroundColor', '#00275e');
		$('#'+list_primary_color).val('#00275e');
		$('.'+list_primary_color+'-sample').css('backgroundColor', '#00275e');
		$('#'+list_second_color).val('#ffffff');
		$('.'+list_second_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_list_main_content_font_color).val('#333333');
		$('.'+mwp_list_main_content_font_color+'-sample').css('backgroundColor', '#333333');
		$('#'+mwp_list_main_content_second_font_color).val('#ffffff');
		$('.'+mwp_list_main_content_second_font_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_list_main_content_heading_color).val('#ffffff');
		$('.'+mwp_list_main_content_heading_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_list_border_color).val('#dddddd');
		$('.'+mwp_list_border_color+'-sample').css('backgroundColor', '#dddddd');
		$('#'+mwp_details_tab_active_background).val('#a60008');
		$('.'+mwp_details_tab_active_background+'-sample').css('backgroundColor', '#a60008');
		$('#'+mwp_details_tab_active_fontcolor).val('#ffffff');
		$('.'+mwp_details_tab_active_fontcolor+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_details_tab_inactive_background).val('#d4d4d4');
		$('.'+mwp_details_tab_inactive_background+'-sample').css('backgroundColor', '#d4d4d4');
		$('#'+mwp_details_tab_inactive_fontcolor).val('#a60008');
		$('.'+mwp_details_tab_inactive_fontcolor+'-sample').css('backgroundColor', '#a60008');
		$('.'+mwp_details_tab_hover_background+'-sample').css('backgroundColor', '#a60008');
		$('#'+mwp_details_tab_hover_background).val('#a60008');
		$('.'+mwp_details_tab_hover_font_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_details_tab_hover_font_color).val('#ffffff');
		$('#'+mwp_details_main_page_background).val('#ffffff');
		$('.'+mwp_details_main_page_background+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_details_main_background).val('#a60008');
		$('.'+mwp_details_main_background+'-sample').css('backgroundColor', '#a60008');
		$('#'+mwp_details_main_font_color).val('#222222');
		$('.'+mwp_details_main_font_color+'-sample').css('backgroundColor', '#222222');
		$('#'+mwp_details_content_main_fontcolor).val('#222222');
		$('.'+mwp_details_content_main_fontcolor+'-sample').css('backgroundColor', '#222222');
		$('#'+mwp_details_content_main_heading_fontcolor).val('#222222');
		$('.'+mwp_details_content_main_heading_fontcolor+'-sample').css('backgroundColor', '#222222');
		$('#'+mwp_details_secondary_background).val('#f0f0f0');
		$('.'+mwp_details_secondary_background+'-sample').css('backgroundColor', '#f0f0f0');
		$('#'+mwp_details_secondary_font_color).val('#a60008');
		$('.'+mwp_details_secondary_font_color+'-sample').css('backgroundColor', '#a60008');
		$('#'+mwp_details_content_secondary_fontcolor).val('#000000');
		$('.'+mwp_details_content_secondary_fontcolor+'-sample').css('backgroundColor', '#000000');
		$('.'+mwp_details_content_border_color+'-sample').css('backgroundColor', '#a60008');
		$('#'+mwp_details_content_border_color).val('#a60008');
		$('#'+mwp_search_main_page_background).val('#ffffff');
		$('.'+mwp_search_main_page_background+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_button_main_background).val('#ffffff');
		$('.'+mwp_button_main_background+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_button_font_color).val('#c00009');
		$('.'+mwp_button_font_color+'-sample').css('backgroundColor', '#c00009');
		$('#'+mwp_button_secondary_background).val('#ffffff');
		$('.'+mwp_button_secondary_background+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_button_secondary_fontcolor).val('#c00009');
		$('.'+mwp_button_secondary_fontcolor+'-sample').css('backgroundColor', '#c00009');
		$('#'+mwp_button_border_color).val('#ffffff');
		$('.'+mwp_button_border_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_header_main_background_color).val('#a60008');
		$('.'+mwp_header_main_background_color+'-sample').css('backgroundColor', '#a60008');
		$('#'+mwp_header_secondary_background_color).val('#b5b5b5');
		$('.'+mwp_header_secondary_background_color+'-sample').css('backgroundColor', '#b5b5b5');
		$('#'+mwp_header_primary_font_color).val('#000000');
		$('.'+mwp_header_primary_font_color+'-sample').css('backgroundColor', '#000000');
		$('#'+mwp_header_secondary_font_color).val('#000000');
		$('.'+mwp_header_secondary_font_color+'-sample').css('backgroundColor', '#000000');
		$('#'+mwp_header_heading_color).val('#000000');
		$('.'+mwp_header_heading_color+'-sample').css('backgroundColor', '#000000');
		$('#'+mwp_header_border_color).val('#a60008');
		$('.'+mwp_header_border_color+'-sample').css('backgroundColor', '#a60008');
	});
	$('.prodigy-capital').click(function(e){
		e.preventDefault();
		$('#'+list_background_color).val('#ffffff');
		$('.'+list_background_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_list_active_label).val('#060');
		$('.'+mwp_list_active_label+'-sample').css('backgroundColor', '#060');
		$('#'+list_second_background_color).val('#00275e');
		$('.'+list_second_background_color+'-sample').css('backgroundColor', '#00275e');
		$('#'+list_primary_color).val('#00275e');
		$('.'+list_primary_color+'-sample').css('backgroundColor', '#00275e');
		$('#'+list_second_color).val('#ffffff');
		$('.'+list_second_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_list_main_content_font_color).val('#333333');
		$('.'+mwp_list_main_content_font_color+'-sample').css('backgroundColor', '#333333');
		$('#'+mwp_list_main_content_second_font_color).val('#ffffff');
		$('.'+mwp_list_main_content_second_font_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_list_main_content_heading_color).val('#ffffff');
		$('.'+mwp_list_main_content_heading_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_list_border_color).val('#dddddd');
		$('.'+mwp_list_border_color+'-sample').css('backgroundColor', '#dddddd');
		$('#'+mwp_details_tab_active_background).val('#16354a');
		$('.'+mwp_details_tab_active_background+'-sample').css('backgroundColor', '#16354a');
		$('#'+mwp_details_tab_active_fontcolor).val('#ffffff');
		$('.'+mwp_details_tab_active_fontcolor+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_details_tab_inactive_background).val('#c3c6c7');
		$('.'+mwp_details_tab_inactive_background+'-sample').css('backgroundColor', '#c3c6c7');
		$('#'+mwp_details_tab_inactive_fontcolor).val('#16354a');
		$('.'+mwp_details_tab_inactive_fontcolor+'-sample').css('backgroundColor', '#16354a');
		$('.'+mwp_details_tab_hover_background+'-sample').css('backgroundColor', '#16354a');
		$('#'+mwp_details_tab_hover_background).val('#16354a');
		$('.'+mwp_details_tab_hover_font_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_details_tab_hover_font_color).val('#ffffff');
		$('#'+mwp_details_main_page_background).val('#ffffff');
		$('.'+mwp_details_main_page_background+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_details_main_background).val('#16354a');
		$('.'+mwp_details_main_background+'-sample').css('backgroundColor', '#16354a');
		$('#'+mwp_details_main_font_color).val('#222222');
		$('.'+mwp_details_main_font_color+'-sample').css('backgroundColor', '#222222');
		$('#'+mwp_details_content_main_fontcolor).val('#222222');
		$('.'+mwp_details_content_main_fontcolor+'-sample').css('backgroundColor', '#222222');
		$('#'+mwp_details_content_main_heading_fontcolor).val('#222222');
		$('.'+mwp_details_content_main_heading_fontcolor+'-sample').css('backgroundColor', '#222222');
		$('#'+mwp_details_secondary_background).val('#f0f0f0');
		$('.'+mwp_details_secondary_background+'-sample').css('backgroundColor', '#f0f0f0');
		$('#'+mwp_details_secondary_font_color).val('#16354a');
		$('.'+mwp_details_secondary_font_color+'-sample').css('backgroundColor', '#16354a');
		$('#'+mwp_details_content_secondary_fontcolor).val('#16354a');
		$('.'+mwp_details_content_secondary_fontcolor+'-sample').css('backgroundColor', '#16354a');
		$('.'+mwp_details_content_border_color+'-sample').css('backgroundColor', '#c3c6c7');
		$('#'+mwp_details_content_border_color).val('#c3c6c7');
		$('#'+mwp_search_main_page_background).val('#ffffff');
		$('.'+mwp_search_main_page_background+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_button_main_background).val('#ffffff');
		$('.'+mwp_button_main_background+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_button_font_color).val('#16354a');
		$('.'+mwp_button_font_color+'-sample').css('backgroundColor', '#16354a');
		$('#'+mwp_button_secondary_background).val('#ffffff');
		$('.'+mwp_button_secondary_background+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_button_secondary_fontcolor).val('#16354a');
		$('.'+mwp_button_secondary_fontcolor+'-sample').css('backgroundColor', '#16354a');
		$('#'+mwp_button_border_color).val('#ffffff');
		$('.'+mwp_button_border_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_header_main_background_color).val('#16354a');
		$('.'+mwp_header_main_background_color+'-sample').css('backgroundColor', '#16354a');
		$('#'+mwp_header_secondary_background_color).val('#d9d9d9');
		$('.'+mwp_header_secondary_background_color+'-sample').css('backgroundColor', '#d9d9d9');
		$('#'+mwp_header_primary_font_color).val('#000000');
		$('.'+mwp_header_primary_font_color+'-sample').css('backgroundColor', '#000000');
		$('#'+mwp_header_secondary_font_color).val('#000000');
		$('.'+mwp_header_secondary_font_color+'-sample').css('backgroundColor', '#000000');
		$('#'+mwp_header_heading_color).val('#000000');
		$('.'+mwp_header_heading_color+'-sample').css('backgroundColor', '#000000');
		$('#'+mwp_header_border_color).val('#16354a');
		$('.'+mwp_header_border_color+'-sample').css('backgroundColor', '#16354a');
	});
	$('.realty-one').click(function(e){
		e.preventDefault();
		$('#'+list_background_color).val('#ffffff');
		$('.'+list_background_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_list_active_label).val('#060');
		$('.'+mwp_list_active_label+'-sample').css('backgroundColor', '#060');
		$('#'+list_second_background_color).val('#00275e');
		$('.'+list_second_background_color+'-sample').css('backgroundColor', '#00275e');
		$('#'+list_primary_color).val('#00275e');
		$('.'+list_primary_color+'-sample').css('backgroundColor', '#00275e');
		$('#'+list_second_color).val('#ffffff');
		$('.'+list_second_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_list_main_content_font_color).val('#333333');
		$('.'+mwp_list_main_content_font_color+'-sample').css('backgroundColor', '#333333');
		$('#'+mwp_list_main_content_second_font_color).val('#ffffff');
		$('.'+mwp_list_main_content_second_font_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_list_main_content_heading_color).val('#ffffff');
		$('.'+mwp_list_main_content_heading_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_list_border_color).val('#dddddd');
		$('.'+mwp_list_border_color+'-sample').css('backgroundColor', '#dddddd');
		$('#'+mwp_details_tab_active_background).val('#222222');
		$('.'+mwp_details_tab_active_background+'-sample').css('backgroundColor', '#222222');
		$('#'+mwp_details_tab_active_fontcolor).val('#ffffff');
		$('.'+mwp_details_tab_active_fontcolor+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_details_tab_inactive_background).val('#000000');
		$('.'+mwp_details_tab_inactive_background+'-sample').css('backgroundColor', '#000000');
		$('#'+mwp_details_tab_inactive_fontcolor).val('#ffffff');
		$('.'+mwp_details_tab_inactive_fontcolor+'-sample').css('backgroundColor', '#ffffff');
		$('.'+mwp_details_tab_hover_background+'-sample').css('backgroundColor', '#222222');
		$('#'+mwp_details_tab_hover_background).val('#222222');
		$('.'+mwp_details_tab_hover_font_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_details_tab_hover_font_color).val('#ffffff');
		$('#'+mwp_details_main_page_background).val('#000000');
		$('.'+mwp_details_main_page_background+'-sample').css('backgroundColor', '#000000');
		$('#'+mwp_details_main_background).val('#ffffff');
		$('.'+mwp_details_main_background+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_details_main_font_color).val('#e8e8e8');
		$('.'+mwp_details_main_font_color+'-sample').css('backgroundColor', '#e8e8e8');
		$('#'+mwp_details_content_main_fontcolor).val('#e8e8e8');
		$('.'+mwp_details_content_main_fontcolor+'-sample').css('backgroundColor', '#e8e8e8');
		$('#'+mwp_details_content_main_heading_fontcolor).val('#e8e8e8');
		$('.'+mwp_details_content_main_heading_fontcolor+'-sample').css('backgroundColor', '#e8e8e8');
		$('#'+mwp_details_secondary_background).val('#171717');
		$('.'+mwp_details_secondary_background+'-sample').css('backgroundColor', '#171717');
		$('#'+mwp_details_secondary_font_color).val('#ffffff');
		$('.'+mwp_details_secondary_font_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_details_content_secondary_fontcolor).val('#ffffff');
		$('.'+mwp_details_content_secondary_fontcolor+'-sample').css('backgroundColor', '#ffffff');
		$('.'+mwp_details_content_border_color+'-sample').css('backgroundColor', '#222222');
		$('#'+mwp_details_content_border_color).val('#222222');
		$('#'+mwp_search_main_page_background).val('#ffffff');
		$('.'+mwp_search_main_page_background+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_button_main_background).val('#000000');
		$('.'+mwp_button_main_background+'-sample').css('backgroundColor', '#000000');
		$('#'+mwp_button_font_color).val('#ffffff');
		$('.'+mwp_button_font_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_button_secondary_background).val('#000000');
		$('.'+mwp_button_secondary_background+'-sample').css('backgroundColor', '#000000');
		$('#'+mwp_button_secondary_fontcolor).val('#ffffff');
		$('.'+mwp_button_secondary_fontcolor+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_button_border_color).val('#000000');
		$('.'+mwp_button_border_color+'-sample').css('backgroundColor', '#000000');
		$('#'+mwp_header_main_background_color).val('#222222');
		$('.'+mwp_header_main_background_color+'-sample').css('backgroundColor', '#222222');
		$('#'+mwp_header_secondary_background_color).val('#000000');
		$('.'+mwp_header_secondary_background_color+'-sample').css('backgroundColor', '#000000');
		$('#'+mwp_header_primary_font_color).val('#ffffff');
		$('.'+mwp_header_primary_font_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_header_secondary_font_color).val('#ffffff');
		$('.'+mwp_header_secondary_font_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_header_heading_color).val('#ffffff');
		$('.'+mwp_header_heading_color+'-sample').css('backgroundColor', '#ffffff');
		$('#'+mwp_header_border_color).val('#000000');
		$('.'+mwp_header_border_color+'-sample').css('backgroundColor', '#000000');
	});
});
